### ISSUE TITLE
missing git tags for v0.083 and v0.084

### ISSUE THREAD

**Issue by spazm** [appium/perl-client#14]
I think these should be at b888f10 and 7b5fd2c respectively.

```
git tag v0.0803 b888f10ac14c7e9c4066b2e00bbcc49bb35244fa
git tag v0.0804 7b5fd2c6ccf9033ce53a1f25eff025d6b300d249
```

**Comment by gempesaw** [comment]
thanks! updated now

https://github.com/appium/perl-client/releases/tag/v0.0804
https://github.com/appium/perl-client/releases/tag/v0.0803
