### ISSUE TITLE
Needs a cpan release for v0.0804

### ISSUE THREAD

**Issue by spazm** [appium/perl-client#15]
CPAN is still on v0.0803 where #10 is still broken, blocking installs.

Please cut a release for the current HEAD and push to cpan.  Thanks!

**Comment by jlipps** [comment]
@gempesaw do you know how to do this?

**Comment by gempesaw** [comment]
hmm, I'm happy to do a release once I get back ftom lunch, but unfortunately I haven't been able to actively maintain the perl bindings for a few years now, so I can't guarantee that they'll be particularly useful...

**Comment by jlipps** [comment]
That's cool, maybe @spazm wants to take over :-)

**Comment by gempesaw** [comment]
Okay, 0.0804 is [out](https://metacpan.org/release/Appium) and it's passing [cpantesters](http://matrix.cpantesters.org/?dist=Appium+0.0804) so far. Cheers!

**Comment by spazm** [comment]
Woot! Thanks.
